### PR TITLE
add edit method

### LINKED ISSUE #7: Add edit method
Add `edit` method so that we can edit existing insights.

This will rely on the `getById` method.

### PR DESCRIPTION
**Pull request by mk4111**
Closes #7 

adds `edit` method which allows users to edit/update existing insights.

Build fails because this PR relies on [insights to be added to mockdata](https://github.com/emfoundation/mock-data/pull/2)

### CODE REVIEW

**Comment by nelsonic** [comment]
https://github.com/dwyl/contributing/issues/37

**Comment by mk4111** [comment]
@nelsonic - sorry!! :fearful: Have cleared the assignees now.

**Comment by nelsonic** [comment]
@mk4111 no need to apologise. you are doing _really_ good work! ❤️ 
It's just a question of ensuring that CI tests/checks are passing `before` assigning to anyone `else`.
***or*** if the tests are _not_ passing, to ask for help if you are stuck. 👍

**Comment by jay-meister** [comment]
@nelsonic it is difficult in our case as we have 6 active repos so any piece of work on one that relies on a pr in a different repo will fail on travis, even though it is perfectly fine and can be reviewed and merged assuming things get merged in in the right order.

**Review by jay-meister — APPROVED** [review]
guten

**Review by SimonLab — APPROVED** [review]
:+1:

**Pull request merged**
